#!/bin/bash

set_loadkeys()
{
    loadkeys lv
}

update_locales()
{
local locale_file=~/test
echo "LANG=en_US.UTF-8" >> $locale_file
echo "LANGUAGE=" >> $locale_file
echo "LC_CTYPE="en_US.UTF-8"" >> $locale_file
echo "LC_NUMERIC=lv_LV.UTF-8" >> $locale_file
echo "LC_TIME=lv_LV.UTF-8" >> $locale_file
echo "LC_COLLATE="en_US.UTF-8"" >> $locale_file
echo "LC_MONETARY=lv_LV.UTF-8" >> $locale_file
echo "LC_MESSAGES="en_US.UTF-8"" >> $locale_file
echo "LC_PAPER=lv_LV.UTF-8" >> $locale_file
echo "LC_NAME=lv_LV.UTF-8" >> $locale_file
echo "LC_ADDRESS=lv_LV.UTF-8" >> $locale_file
echo "LC_TELEPHONE=lv_LV.UTF-8" >> $locale_file
echo "LC_MEASUREMENT=lv_LV.UTF-8" >> $locale_file
echo "LC_IDENTIFICATION=lv_LV.UTF-8" >> $locale_file
echo "LC_ALL=" >> $locale_file
}

set_keyboard()
{
local keyboard_file=~/test
echo "KEYMAP=lv" >> /etc/vconsole.conf

}

update_xkeyboard()
{
    setxkbmap lv apostrophe
}

setup()
{
    "Sdsd"
}
setup
