#!/bin/bash

aur_packages="dmenu-git polybar-git betterlockscreen"
driver_packages="xf86-video-qxl xf86-input-libinput xdo xorg-server xorg-xinit"
terminal_packages="termite"
aur_fonts="ttf-ms-fonts"
util_packages="bspwm sxhkd feh rofi firefox libreoffice-fresh lxappearance-gtk3 arc-gtk-theme neofetch htop brightnessctl"

symlink_folders()
{
ln -s ~/Github/dotfiles/bspwm ~/.config/bspwm
ln -s ~/Github/dotfiles/sxhkd ~/.config/sxhkd
ln -s ~/Github/dotfiles/polybar ~/.config/polybar
}
setxkeyboard()
{
sudo localectl set-x11-keymap lv apostrophe
}

create_config_files()
{
echo "export TERMINAL=termite" >> ~/.bashrc
echo "export EDITOR=vim" >> ~/.bashrc
touch ~/.xinitrc
echo "exec bspwm" >> ~/.xinitrc
mkdir ~/.config/termite
sudo cp /etc/xdg/termite/config ~/.config/termite/
}

install_packages()
{
sudo pacman -S $driver_packages $terminal_packages $util_packages
}

install_aur_packages()
{
git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && yay -S $aur_packages && yay --editmenu -S $aur_fonts
}

install_packages && install_aur_packages && symlink_folders && create_config_files && setxkeyboard 

