#!/bin/sh
bspc rule -r "*"

sxhkd &

$HOME/.config/bspwm/fehbg &&

$HOME/.config/polybar/launch.sh &

nm-applet &

setxkbmap -layout lv apostrophe

###---Monitors Config---###
bspc monitor -d 1 2 3 4 5

###---Monitor and Desktop Settings---###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10
